//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetVehicles.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.FleetCars = new HashSet<FleetCars>();
        }
    
        public int IdCar { get; set; }
        public Nullable<int> IdModel { get; set; }
        public Nullable<int> IdBody { get; set; }
        public Nullable<int> NumberOfSeats { get; set; }
        public Nullable<int> LoadCapacity { get; set; }
    
        public virtual BodyType BodyType { get; set; }
        public virtual CarModel CarModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FleetCars> FleetCars { get; set; }
    }
}
