//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetVehicles.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FleetCars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FleetCars()
        {
            this.InsurancePolicy = new HashSet<InsurancePolicy>();
        }
    
        public int IdFleetCar { get; set; }
        public Nullable<int> IdDriver { get; set; }
        public Nullable<int> IdCar { get; set; }
        public string VinNumber { get; set; }
        public string RegistrationNumber { get; set; }
        public Nullable<int> IdColor { get; set; }
    
        public virtual CarColor CarColor { get; set; }
        public virtual Cars Cars { get; set; }
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsurancePolicy> InsurancePolicy { get; set; }
    }
}
