//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetVehicles.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsurancePolicy
    {
        public int IdInsurance { get; set; }
        public Nullable<int> IdFleetCar { get; set; }
        public string Type { get; set; }
        public string Number { get; set; }
        public string Series { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public Nullable<System.DateTime> DateOfExpiry { get; set; }
    
        public virtual FleetCars FleetCars { get; set; }
    }
}
