//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetVehicles.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAdditionalService
    {
        public int IdOrderAdditionalService { get; set; }
        public Nullable<int> IdAdditionalService { get; set; }
        public Nullable<int> IdOrder { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual AdditionalService AdditionalService { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
