//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetVehicles.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderAdditionalService = new HashSet<OrderAdditionalService>();
        }
    
        public int IdOrder { get; set; }
        public Nullable<int> IdCustomer { get; set; }
        public Nullable<int> IdFleetCar { get; set; }
        public Nullable<int> IdTariff { get; set; }
        public Nullable<int> TotalCost { get; set; }
        public Nullable<int> NumberOfPassengers { get; set; }
        public string DepartureAddress { get; set; }
        public string ArrivalAddress { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> IdDispatcher { get; set; }
        public string Notes { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual FleetCars FleetCars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderAdditionalService> OrderAdditionalService { get; set; }
        public virtual Tariff Tariff { get; set; }
    }
}
